version: "3.8"
services:
  receiver:
    build:
      context: ./receiver
      dockerfile: Dockerfile
    container_name: comfyui-receiver
    restart: unless-stopped
    environment:
      - SAVE_DIR=/data
    volumes:
      - ./data:/data
    ports:
      - "18080:8000"

  samba:
    image: dperson/samba:latest
    container_name: comfyui-samba
    restart: unless-stopped
    depends_on:
      - receiver
    environment:
      - TZ=UTC
    command: [
      "-s", "images;/data;yes;no;yes;all;none;none",
      "-u", "${SAMBA_USER:-pi};${SAMBA_PASS:-raspberry}",
      "-p"
    ]
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - ./data:/data

  drive_fetcher:
    build:
      context: ./drive_fetcher
      dockerfile: Dockerfile
    container_name: drive-fetcher
    restart: unless-stopped
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/creds/service_account.json
      - DOWNLOAD_DIR=/downloads
      - DRIVE_QUERY=mimeType contains 'image/'
      - POLL_INTERVAL=60
      # Optional: 指定フォルダのみ監視する場合は環境変数で設定
      # - DRIVE_FOLDER_ID=xxxxxxxxxxxxxxxxxxxx
    volumes:
      - ./drive_creds:/creds:ro
      - ./downloads:/downloads

# Notes:
# - Samba runs with host networking to expose SMB ports directly on the LAN.
# - Receiver is published on port 8000; reach it via Tailscale IP:8000.
